#### Model taken from:
- [1] Offshore Pipelaying Dynamics. Gullik Anthon Jensen 
- [2] A nonlinear PDE formulation for offshore vessel pipeline installation. Gullik A. Jensen et al 
- [3] Modeling and Control of Offshore Pipelay Operations Based on a Finite Strain Pipe Model. Gullik A. Jensen 

In [1]:
import numpy as np
import numdifftools as nd
import math

In [2]:
mp = 96 #  (submerged) [kg/m]

In [3]:
diag_Irho = 1e2*np.array([1, 1, 2]) # [m^4]  , p.99 in [1]
 
Irho=np.diag(diag_Irho)

In [4]:
Irho

array([[100.,   0.,   0.],
       [  0., 100.,   0.],
       [  0.,   0., 200.]])

In [5]:
qw = 1025 # Water density [kg/m3]
d0 = 0.761 # Outer diameter of pipe, [m]

In [6]:
diag_DT = 1.5*np.array([1, 1, 1]) # [N/m]  , p.99 in [1]

In [7]:
DT=np.diag(diag_DT) # (35) in [2]

In [8]:
DT

array([[1.5, 0. , 0. ],
       [0. , 1.5, 0. ],
       [0. , 0. , 1.5]])

In [9]:
diag_CT = 1e9*np.array([1, 1, 1]) # p. 4721 in [3]

In [10]:
CT=np.diag(diag_CT)

In [11]:
from sympy import *

In [12]:
# Dphi1, Dphi2, Dphi3 = symbols("Dphi1 Dphi2 Dphi3")
dx,dy,dz=.3,4,5

In [13]:
def C1(dx,dy,dz):
    return np.array([dx**2,
          (dy**2+dz**2)**0.5*dy,
          (dy**2+dz**2)**0.5*dz]).T

In [14]:
DT

array([[1.5, 0. , 0. ],
       [0. , 1.5, 0. ],
       [0. , 0. , 1.5]])

In [15]:
def fD(dx,dy,dz,DT):
    return 1/2*d0*qw*np.dot(DT, C1(dx,dy,dz))

In [16]:
fD(dx,dy,dz,DT)

array([   52.6516875 , 14983.79094991, 18729.73868739])

In [17]:
# https://docs.scipy.org/doc/scipy-1.8.0/tutorial/integrate.html  
# 1-D Gray-Scott 

In [18]:
# Mat=np.matrix([[1.3,.4,6.7],[9,7,6],[3.3,5.6,7]])

In [19]:
I=np.identity(3)

In [20]:
fD(dx,dy,dz,DT)

array([   52.6516875 , 14983.79094991, 18729.73868739])

In [21]:
np.dot(I,fD(dx,dy,dz,DT))

array([   52.6516875 , 14983.79094991, 18729.73868739])

In [22]:
Rb_t=I # https://www.researchgate.net/profile/Thor-Fossen/publication/224560837_Modeling_and_Control_of_Offshore_Pipelay_Operations_Based_on_a_Finite_Strain_Pipe_Model/links/00b7d520e175a3f918000000/Modeling-and-Control-of-Offshore-Pipelay-Operations-Based-on-a-Finite-Strain-Pipe-Model.pdf

In [23]:
Rb_t

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
diag_DR = 1.5*np.array([1, 1, 1]) #   p.4721 in [3]

In [25]:
DR=np.diag(diag_DR) 

In [26]:
dI= 0.69# Inner diameter of pipe, [m]

In [27]:
A=math.pi*((d0/2)**2-(dI/2)**2)

In [28]:
fg_e=np.array([0,0,(mp-qw*A)*9.81])

In [29]:
from numpy import linalg as LA

In [30]:
def k_sigma(hi,d0,fg_e):
    if hi<0:
        return 0
    elif 0<=hi<=d0/20:
        return LA.norm(fg_e,2)/(d0/8-d0/40)*10*hi**2/d0
    else:
        return LA.norm(fg_e,2)/(d0/8-d0/40)*(hi-d0/40)

In [31]:
def hi(x,y,z,d0):
    return np.dot(np.array([x,y,z]).T,[0,0,1])+d0/2 

In [32]:
x,y,z=np.array([2.3,3.5,7])

In [33]:
def sigma(x,y,z):
    return k_sigma(hi(x,y,z,d0),d0,fg_e)*np.array([0,0,1])

In [34]:
# angles should be in radians, otherwise np.radians them  
def Re_t(φ,θ,ψ):
    Cφ=np.matrix([[1,0,0],
                  [0,np.cos(φ),-np.sin(φ)],
                  [0,np.sin(φ),np.cos(φ)]])
    
    Cθ=np.matrix([[np.cos(θ),0,np.sin(θ)],
                  [0,1,0],
                  [-np.sin(θ),0,np.cos(θ)]])
    
    Cψ=np.matrix([[np.cos(ψ),-np.sin(ψ),0],
                  [np.sin(ψ),np.cos(ψ),0],
                  [0,0,1]])
    
    return np.dot(np.dot(Cφ,Cθ),Cψ)

In [35]:
# vessel motion
# Fossen book p.384
# Fossen paper, section 6

In [36]:
# Fossen paper, equation (12)

In [37]:
φ,θ,ψ=0,1,2

In [38]:
def Re_b(φ,θ,ψ):
    return np.dot(Re_t(φ,θ,ψ), Rb_t ) # (5) in[3]

In [39]:
# p=np.dot(Re_b, phi) # (41) in[3]

In [201]:
def d_s(da,db,dc,dt,ds):
    return np.array([da*dt/ds,db*dt/ds,dc*dt/ds])

In [202]:
x=[0,0.1]
y=[1,3]
z=[4,5]
ds=0.1

In [203]:
def ne(x,y,z,φ,θ,ψ,dt,ds):
    return np.dot(np.dot(np.dot(Re_t(φ,θ,ψ),CT),
                         Re_t(φ,θ,ψ).T), 
                  d_s(dx,dy,dz,dt,ds))

In [204]:
def ne_(x,y,z,dx,dy,dz):
    return -fg_e-fD(dx,dy,dz,DT)-sigma(x,y,z)

In [205]:
# mp*ddp = d_s(ne,ds)+np.dot(Re_b,ne_)

In [206]:
dt=.01

In [207]:
ne(x,y,z,φ,θ,ψ,dt,ds)

matrix([[2.5e+06, 4.0e+08, 5.0e+08]])

In [208]:
def Irho_e(φ,θ,ψ):
    return np.dot(np.dot(Re_t(φ,θ,ψ),Irho),Re_t(φ,θ,ψ).T) # (19) in [3] 

In [209]:
def  Π(φ,θ,ψ):
    return np.matrix([[np.cos(θ)*np.cos(ψ),-np.sin(ψ),0],
                  [np.cos(θ)*np.sin(ψ),np.cos(ψ),0],
                  [-np.sin(θ),0,1]])

In [210]:
def ωe(φ,θ,ψ):
    return np.dot(Π(φ,θ,ψ),np.array([φ,θ,ψ]))  # (100) in [2]

In [211]:
diag_CR = 1e11*np.array([1, 1, 1]) 
 
CR=np.diag(diag_CR)

In [212]:
def me(φ,θ,ψ):
    return np.dot(np.dot(np.dot(Re_t(φ,θ,ψ),CR),Re_t(φ,θ,ψ).T), ωe(φ,θ,ψ).T)

In [213]:
me_=me(φ,θ,ψ)

In [214]:
int(me_[0])

-90929742682

In [215]:
diag_DR = 1.5*np.array([1, 1, 1]) 
 
DR=np.diag(diag_DR)

In [216]:
# np.dot(Re_b, np.dot( Irho_e, (np.dot(Π(φ,θ,ψ), np.array([ddφ,ddθ,ddψ])))))=
# -np.dot(Re_b,np.dot(Irho_e,np.dot(Π(dφ,dθ,dψ),np.array([dφ,dθ,dψ])))-
# np.cross(np.dot(Π(φ,θ,ψ),np.array([dφ,dθ,dψ])),np.dot(Π(φ,θ,ψ),np.array([dφ,dθ,dψ]))))+
# np.dot(Re_b,d_s(me_[0],me_[1],me_[2],dt,ds)+d_s(me_[0],me_[1],me_[2],dt,ds))+
# np.cross(d_s(x,y,z,dt,ds),ne(x,y,z,φ,θ,ψ,dt,ds))+
# np.dot(Re_b,-np.dot(DR,np.dot(Π(φ,θ,ψ),np.array([dφ,dθ,dψ]))))

In [264]:
def grayscott1d(Q, t, ds):
    x,y,z=Q[0],Q[1],Q[2]
    dx,dy,dz=Q[3],Q[4],Q[5]
    φ,θ,ψ=Q[6],Q[7],Q[8]
    dφ,dθ,dψ=Q[9],Q[10],Q[11]
    
    C=ne(x,y,z,φ,θ,ψ,dt,ds)
    a,b,c=C[0,0],C[0,1],C[0,2]
    ddx,ddy, ddz = (1/mp*(d_s(a,b,c,dt,ds)
                                        +np.dot(Re_b(φ,θ,ψ),ne_(x,y,z,dx,dy,dz)))).reshape(3, 1)
    
    me_=me(φ,θ,ψ)
    
    
    B=(-np.dot(Re_b(φ,θ,ψ),np.dot(Irho_e(φ,θ,ψ),np.dot(Π(dφ,dθ,dψ),np.array([dφ,dθ,dψ]).reshape(3,1)))
               -
       np.cross(np.squeeze(np.asarray(np.dot(Π(φ,θ,ψ),np.array([dφ,dθ,dψ]).reshape(3,1)))),
                 np.squeeze(np.asarray(np.dot(Π(φ,θ,ψ),np.array([dφ,dθ,dψ]).reshape(3,1))))).reshape(3,1))
       +
        np.dot(Re_b(φ,θ,ψ),np.squeeze(np.asarray(d_s(me_[0],me_[1],me_[2],dt,ds))).reshape(3,1))
       +
        np.squeeze(np.asarray(np.cross(d_s(x,y,z,dt,ds),ne(x,y,z,φ,θ,ψ,dt,ds)))).reshape(3,1)
       +
        np.dot(Re_b(φ,θ,ψ),-np.dot(DR,np.dot(Π(φ,θ,ψ),np.array([dφ,dθ,dψ]).reshape(3,1))))
      )

    ddφ,ddθ,ddψ = np.linalg.lstsq(np.dot(np.dot(Re_b(φ,θ,ψ),Irho_e(φ,θ,ψ)),Π(φ,θ,ψ)),B, rcond=None)[0]  
    
    return [dx, ddx, dy, ddy, dz, ddz, dφ, ddφ, dθ, ddθ, dψ, ddψ]
    

In [275]:
q0=[i for i in range(12)]
max_t = 10  
dt = 0.5
t=np.arange(0,max_t,dt)
ds = 0.025

In [276]:
from datetime import datetime
from scipy.integrate import odeint

In [277]:
startTime1 = datetime.now()
us=odeint(grayscott1d, q0, t, args=(ds,))
print(datetime.now() - startTime1)

0:00:02.687388


In [278]:
us.shape

(20, 12)

In [279]:
us

array([[0.00000000e+000, 1.00000000e+000, 2.00000000e+000,
        3.00000000e+000, 4.00000000e+000, 5.00000000e+000,
        6.00000000e+000, 7.00000000e+000, 8.00000000e+000,
        9.00000000e+000, 1.00000000e+001, 1.10000000e+001],
       [3.48952120e-005, 7.49322256e+000, 2.00000026e+000,
        1.07838470e+003, 4.00004370e+000, 1.34941025e+003,
        6.00017521e+000, 7.48983872e+000, 8.00000065e+000,
        5.71587382e+003, 1.00001680e+001, 6.71223632e+003],
       [6.93975391e-310, 9.88131292e-324, 2.86558075e-322,
        6.93956284e-310, 1.42290906e-321, 3.95252517e-323,
        6.93975610e-310, 6.93975391e-310, 9.88131292e-324,
        6.93956284e-310, 1.77863633e-321, 4.44659081e-323],
       [6.93975610e-310, 6.93975391e-310, 6.34218421e+206,
        6.93975249e-310, 6.93975635e-310, 6.93975632e-310,
        6.93956284e-310, 2.13436359e-321, 3.45845952e-323,
        6.93975610e-310, 6.93975391e-310, 4.94065646e-324],
       [4.94065646e-324, 6.93975632e-310, 6.93956284

In [ ]:
def psi(gamma,omega,Ct,Cr):
    coord=np.concatenate((gamma, omega), axis=0)
    zero=np.zeros((3,3))
    M1=np.concatenate((Ct, zero), axis=0)
    M2=np.concatenate((zero, Cr), axis=0)
    M=np.concatenate((M1, M2), axis=1)
    return 1/2*np.dot(np.dot(coord.T,M),coord)

In [ ]:
from sympy import *

In [ ]:
gamma1, gamma2,gamma3 = symbols("gamma1 gamma2 gamma3")
omega1, omega2,omega3 = symbols("omega1 omega2 omega3")

In [ ]:
gamma=np.array([gamma1, gamma2,gamma3])
omega=np.array([omega1, omega2,omega3])

In [ ]:
Ct=np.matrix([[1,0,0],[0,2,0],[0,0,3]])
Cr=np.matrix([[4,0,0],[0,5,0],[0,0,6]])

In [ ]:
psi(gamma,omega,Ct,Cr)

In [ ]:
fun = lambda x, y: psi(x,y,Ct,Cr)

In [ ]:
Dfun = nd.Gradient(fun)

In [ ]:
Dfun()

In [ ]:
# coord=np.concatenate((gamma, omega), axis=0)

In [ ]:
gamma

In [ ]:
omega

In [ ]:
Dfun(gamma,omega)

In [ ]:
Dfun